[package]
name = "native_imaging"
version = "0.1.0"
edition = "2024"

[lib]
name = "native_imaging"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
image = "0.25"
fast_image_resize = "5.1"
rayon = "1.10"
walkdir = "2.5"
